a = int (input("Please enter integer number: "))
b = int (input("Please enter integer number: "))
c = int (input("Please enter integer number: "))
d = int (input("Please enter integer number: "))
print(a)
print(b)
print(c)
print(d)

a; b; c; d = int (input("Please enter a four-digit whole number: "))
print(a)
print(b)
print(c)
print(d)
